<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.swiftcache</groupId>
    <artifactId>swiftcache</artifactId>
    <packaging>pom</packaging>
    <version>1.0.1</version>
    <modules>
        <module>swiftcache-api</module>
        <module>swiftcache-core</module>
        <module>swiftcache-test</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.compiler.level>17</project.compiler.level>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--============================== SELF ==============================-->
            <dependency>
                <groupId>io.swiftcache</groupId>
                <artifactId>swiftcache-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swiftcache</groupId>
                <artifactId>swiftcache-core</artifactId>
                <version>${project.version}</version>
            </dependency>


        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${project.compiler.level}</source>
                    <target>${project.compiler.level}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <name>swiftcache</name>
    <description>A lightweight Java caching library.</description>


</project>
